# Generated by Django 4.1.7 on 2023-03-12 00:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=64)),
                ('data', models.DateField()),
                ('diasemana', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.IntegerField()),
                ('confirma', models.BooleanField()),
                ('horario', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('cursoparticipado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Congresso.cursos')),
            ],
        ),
    ]
